services:
  - type: web
    name: admin-whatsapp-backend
    env: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PUPPETEER_CACHE_DIR
        value: /opt/render/project/src/backend/.cache/puppeteer
